from qfluentwidgets import PushButton, PrimaryPushButton,LineEdit,ListWidget,TextEdit,ComboBox
from qfluentwidgets import FluentIcon as FIF
from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        monitor_type_data = [
            "0 - Zabbix agent",
            "2 - Zabbix 采集器",
            "3 - 简单检查",
            "5 - Zabbix 内部检查",
            "7 - Zabbix agent (主动)",
            "10 - 外部检查",
            "11 - 数据库监控",
            "12 - IPMI agent",
            "13 - SSH agent",
            "14 - TELNET agent",
            "15 - 可计算的监控",
            "16 - JMX agent",
            "17 - SNMP trap",
            "18 - 相关项监控",
            "19 - HTTP agent",
            "20 - SNMP agent",
            "21 - 脚本"
        ]
        value_type_data = [
            "0 - 浮点数",
            "1 - 字符",
            "2 - 日志",
            "3 - 数字(无正负)",
            "4 - 文本"
        ]
        Form.setObjectName("Form")
        Form.resize(1500, 600)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.traffic = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.traffic.sizePolicy().hasHeightForWidth())
        self.traffic.setSizePolicy(sizePolicy)
        self.traffic.setMaximumSize(QtCore.QSize(395, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.traffic.setFont(font)
        self.traffic.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.traffic.setObjectName("traffic")
        self.horizontalLayout_8.addWidget(self.traffic)
        self.traffic_comboBox = ComboBox()
        self.traffic_comboBox.setPlaceholderText("选择一个交换机")
        self.traffic_comboBox.setObjectName("traffic_comboBox")
        self.horizontalLayout_8.addWidget(self.traffic_comboBox)
        self.hostid_label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hostid_label.setFont(font)
        self.hostid_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hostid_label.setObjectName("hostid_label")
        self.hostid_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.horizontalLayout_8.addWidget(self.hostid_label)        
        # self.horizontalLayout_8.setStretch(0, 1)
        # self.horizontalLayout_8.setStretch(1, 6)
        # self.horizontalLayout_8.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        
        self.hostname_label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hostname_label.setFont(font)
        self.hostname_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hostname_label.setObjectName("hostname_label")
        self.hostname_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.horizontalLayout_8.addWidget(self.hostname_label)        
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 4)
        self.horizontalLayout_8.setStretch(2, 1)
        self.horizontalLayout_8.setStretch(3, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.monitor = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.monitor.setFont(font)
        self.monitor.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.monitor.setObjectName("monitor")
        self.horizontalLayout_9.addWidget(self.monitor)
        self.monitor_listWidget = ListWidget()
        self.monitor_listWidget.setObjectName("monitor_listWidget")
        self.monitor_listWidget.setSelectionMode(QtWidgets.QListWidget.SelectionMode.MultiSelection)    
        self.horizontalLayout_9.addWidget(self.monitor_listWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.insert_pushButton = PushButton('>>')
        self.insert_pushButton.setFont(font)
        self.insert_pushButton.setObjectName("insert_pushButton")
        self.horizontalLayout_9.addWidget(self.insert_pushButton)        
        self.monitor_listWidget_in = ListWidget()
        self.monitor_listWidget_in.setObjectName("monitor_listWidget_in")       
        self.horizontalLayout_9.addWidget(self.monitor_listWidget_in)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 3)
        self.horizontalLayout_9.setStretch(2, 1)
        self.horizontalLayout_9.setStretch(3, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.monitor_name = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.monitor_name.setFont(font)
        self.monitor_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.monitor_name.setObjectName("monitor_name")
        self.horizontalLayout.addWidget(self.monitor_name)
        self.monitor_name_lineEdit = LineEdit()
        self.monitor_name_lineEdit.setPlaceholderText("请输入监控项名称")
        self.monitor_name_lineEdit.setObjectName("monitor_name_lineEdit")
        self.horizontalLayout.addWidget(self.monitor_name_lineEdit)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 6)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.monitor_type = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.monitor_type.setFont(font)
        self.monitor_type.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.monitor_type.setObjectName("monitor_type")
        self.horizontalLayout_2.addWidget(self.monitor_type)
        self.monitor_type_comboBox = ComboBox()
        self.monitor_type_comboBox.setObjectName("monitor_type_comboBox")
        self.monitor_type_comboBox.addItems(monitor_type_data)
        self.horizontalLayout_2.addWidget(self.monitor_type_comboBox)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 6)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.monitor_key = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.monitor_key.setFont(font)
        self.monitor_key.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.monitor_key.setObjectName("monitor_key")
        self.horizontalLayout_3.addWidget(self.monitor_key)
        self.monitor_key_lineedit = LineEdit()
        self.monitor_key_lineedit.setPlaceholderText("net.all.out[AllOut.1]")
        self.monitor_key_lineedit.setText("net.all.out[AllOut.1]")
        self.monitor_key_lineedit.setObjectName("monitor_key_lineedit")
        self.horizontalLayout_3.addWidget(self.monitor_key_lineedit)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 6)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.info_type = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_type.setFont(font)
        self.info_type.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.info_type.setObjectName("info_type")
        self.horizontalLayout_4.addWidget(self.info_type)
        self.info_type_comboBox = ComboBox()
        self.info_type_comboBox.setObjectName("info_type_comboBox")
        self.info_type_comboBox.addItems(value_type_data)
        self.horizontalLayout_4.addWidget(self.info_type_comboBox)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 6)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.param = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.param.setFont(font)
        self.param.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.param.setObjectName("param")
        self.horizontalLayout_5.addWidget(self.param)
        self.param_textEdit = TextEdit()
        self.param_textEdit.setObjectName("param_textEdit")
        self.param_textEdit.setPlainText("last(/CHN-LNdalian-WXnode/net.if.out[ifHCOutOctets.201])+last(/CHN-LNdalian-WXnode/net.if.out[ifHCOutOctets.202]) ")
        self.horizontalLayout_5.addWidget(self.param_textEdit)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 6)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.update_time = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.update_time.setFont(font)
        self.update_time.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.update_time.setObjectName("update_time")
        self.horizontalLayout_6.addWidget(self.update_time)
        self.update_time_lineEdit = LineEdit()
        self.update_time_lineEdit.setText("1m")
        self.update_time_lineEdit.setReadOnly(True)
        self.update_time_lineEdit.setObjectName("update_time_lineEdit")
        self.horizontalLayout_6.addWidget(self.update_time_lineEdit)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 5)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tag = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tag.setFont(font)
        self.tag.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tag.setObjectName("tag")
        self.horizontalLayout_7.addWidget(self.tag)
        self.tag_lineEdit = LineEdit()
        self.tag_lineEdit.setText("jiankong")
        self.tag_lineEdit.setReadOnly(True)
        self.tag_lineEdit.setObjectName("tag_lineEdit")
        self.horizontalLayout_7.addWidget(self.tag_lineEdit)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 5)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.create_pushButton = PrimaryPushButton('创建聚合')
        font = QtGui.QFont()
        font.setPointSize(12)
        self.create_pushButton.setFont(font)
        self.create_pushButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.create_pushButton.setObjectName("create_pushButton")
        self.gridLayout_4.addWidget(self.create_pushButton, 2, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.traffic.setText(_translate("Form", "交换机"))
        self.hostid_label.setText(_translate("Form", "HOSTID"))
        self.hostname_label.setText(_translate("Form", "主机名"))
        self.monitor.setText(_translate("Form", "监控项"))
        self.monitor_name.setText(_translate("Form", "监控项名称"))
        self.monitor_type.setText(_translate("Form", "监控类型"))
        self.monitor_key.setText(_translate("Form", "键值"))
        self.info_type.setText(_translate("Form", "信息类型"))
        self.param.setText(_translate("Form", "公式"))
        self.update_time.setText(_translate("Form", "更新间隔"))
        self.tag.setText(_translate("Form", "标签名称"))
