# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\0Work\py-tools\pymark\pymark.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from watermarker.marker import add_mark
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(865, 278)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_open = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_open.setFont(font)
        self.pushButton_open.setObjectName("pushButton_open")
        self.gridLayout.addWidget(self.pushButton_open, 0, 0, 1, 1)
        self.lineEdit_pic = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pic.setObjectName("lineEdit_pic")
        self.gridLayout.addWidget(self.lineEdit_pic, 0, 1, 1, 1)
        self.pushButton_outpath = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_outpath.setFont(font)
        self.pushButton_outpath.setObjectName("pushButton_outpath")
        self.gridLayout.addWidget(self.pushButton_outpath, 1, 0, 1, 1)
        self.lineEdit_outpath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_outpath.setObjectName("lineEdit_outpath")
        self.gridLayout.addWidget(self.lineEdit_outpath, 1, 1, 1, 1)
        self.label_font = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_font.setFont(font)
        self.label_font.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_font.setObjectName("label_font")
        self.gridLayout.addWidget(self.label_font, 2, 0, 1, 1)
        self.lineEdit_font = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_font.setObjectName("lineEdit_font")
        self.gridLayout.addWidget(self.lineEdit_font, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(284, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.pushButton_output = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_output.setFont(font)
        self.pushButton_output.setObjectName("pushButton_output")
        self.gridLayout_2.addWidget(self.pushButton_output, 0, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 6)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 2)
        self.verticalLayout.addLayout(self.gridLayout_2)
        mainWindow.setCentralWidget(self.centralwidget)

        mainWindow.setWindowIcon(QtGui.QIcon('./mark.ico'))
        
        self.retranslateUi(mainWindow)
        self.pushButton_open.clicked.connect(self.get_pic_path) # type: ignore
        self.pushButton_output.clicked.connect(self.add_mask_in) # type: ignore
        self.pushButton_outpath.clicked.connect(self.get_pic_out_path)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "图片加水印 --1.0.1"))
        self.pushButton_open.setText(_translate("mainWindow", "打开图片"))
        self.pushButton_outpath.setText(_translate("mainWindow", "导出路径"))
        self.label_font.setText(_translate("mainWindow", "设置水印字："))
        self.pushButton_output.setText(_translate("mainWindow", "导出"))

     #获取图片路径并显示在edit上
    def get_pic_path(self):
       # pic_path = QtWidgets.QFileDialog.getExistingDirectory(None,"选择文件夹","./")
        pic_path, filetype= QtWidgets.QFileDialog.getOpenFileName(None,"选择图片","./","All Files(*)")
        self.lineEdit_pic.setText(pic_path)
    
    def get_pic_out_path(self):
        pic_out_path = QtWidgets.QFileDialog.getExistingDirectory(None,"选择文件夹","./")
        self.lineEdit_outpath.setText(pic_out_path)
    #配置水印
    def add_mask_in(self):
        pic_path = self.lineEdit_pic.text()
        font_in = self.lineEdit_font.text()
        out_path = self.lineEdit_outpath.text()
        add_mark(pic_path,mark=font_in,out=out_path,size=60,opacity=0.2,space=180,angle=35) 
        QtWidgets.QMessageBox.warning(self,"提示","已导出带水印图片",QtWidgets.QMessageBox.Yes)